language: elixir
elixir: 1.3.4
otp_release: 18.3
sudo: false
addons:
  postgresql: 9.4
before_script:
  - MIX_ENV=test mix compile
  - MIX_ENV=test mix ecto.create
script:
  - mix test
  - echo "Re-running tests for each app" ; for app in apps/**; do cd $app && mix test; cd ../.. ; done
